### ISSUE TITLE
logging problem?

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/RMextract#19]
The code works fine, just when I run it I get this unclear error at the beginning:

.:[fdg]:. @ lofar3:~/data2/bootes/obs1/cals$ createRMh5parm.py 3c196_t1800_SB186.MS 3c196_t1800_SB186.MS/rme.h5
pyrap will be used to compute positions
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file createRMh5parm.py, line 153

**Comment by gmloose** [comment]
I guess this is no longer an issue. Last comment is almost 6 years old.
