### ISSUE TITLE
calls to ftp vs looking in IONEXdata

### ISSUE THREAD

**Issue by twillis449** [lofar-astron/RMextract#27]
Hi Maaijke

In RMextract V0.4 it looks like you first try to ftp the IONEX files before you look in the IONEXdata directory to check if they have already been downloaded.  Could you reverse this sequence? This is just a minor grip, but it affects me at work as every so often the current system there drops  the line to the outside world until I sign into a web browser and check that I agree with working 'Terms and Conditions'. It I haven't done that recently. the system produces an error message when I try to run RMextract, even if I already have downloaded the IONEX files.

Here's the nonsense that gets spitted out if I forget to say I agree to Terms and Conditions - grrrr!

Traceback (most recent call last):
  File "RMextract_multi_dir.py", line 381, in <module>
    main(sys.argv)
  File "RMextract_multi_dir.py", line 354, in main
    process_RMextract(MSname=MSname, object= obj, num_processors=8, timestep=TIME_STEP,pointing_positions_file=pointing_file)
  File "RMextract_multi_dir.py", line 269, in process_RMextract
    res = getRM(*args, **kw) 
  File "/usr/local/lib/python2.7/dist-packages/RMextract-0.1-py2.7-linux-x86_64.egg/RMextract/getRM.py", line 153, in getRM
    ionexf=ionex.getIONEXfile(time=date_parms,server=server,prefix=prefix,outpath=ionexPath)
  File "/usr/local/lib/python2.7/dist-packages/RMextract-0.1-py2.7-linux-x86_64.egg/RMextract/getIONEX.py", line 564, in getIONEXfile
    return _get_IONEX_file(time, server, prefix, outpath, overwrite)
  File "/usr/local/lib/python2.7/dist-packages/RMextract-0.1-py2.7-linux-x86_64.egg/RMextract/getIONEX.py", line 476, in _get_IONEX_file
    ftp = ftplib.FTP(ftpserver)
  File "/usr/lib/python2.7/ftplib.py", line 120, in __init__
    self.connect(host)
  File "/usr/lib/python2.7/ftplib.py", line 138, in connect
    self.welcome = self.getresp()
  File "/usr/lib/python2.7/ftplib.py", line 224, in getresp
    raise error_temp, resp
ftplib.error_temp: 421 Firewall requires that you agree to the disclaimer using a web browser before proceeding with this service

**Comment by maaijke** [comment]
Thanks.This was a bug.

**Comment by maaijke** [comment]
I now made it such that thefiles are always stored in lowercase (this sometimes depends on the server). So it might be it still doesn't find the files you stored in the past.
